### ISSUE TITLE
[Feature Request] 1.15.2 Admin Store for servers ideas

### ISSUE THREAD

**Issue by mr-poyo** [FifouBE/EconomyInc#23]
Hello,

Great mod! Thank you! I would love an Admin store feature. I am currently working on a server and am using Economy Inc as the currency mod. I see huge potential in putting vending blocks at spawn to encourage players to return to spawn for "shopping." 

**Some ideas I hope you will consider for this mod:**

- When a vending block is placed in creative mode, perhaps have the ownerName assigned to a dummy player. Currently, it assigns to the player who placed it, which makes dual-roles (Admin/player) difficult on a server and require workarounds (ignore funds, remove funds, etc). A dummy player would always have "0" funds to recover" (perhaps?).

- Allow an Admin placed vending block to run commands as a "purchasable item" such as **/give @p minecraft:diamond 1** or **/say hi**. This may be harder to implement, but it would allow much more creative ways to use the mod especially if target selectors like **@p, @s** are accepted. 

Thank you for reading!

**Comment by Florent98** [comment]
Hello, 

- The problem of assigning it to a dummy player means that block couldn't be access back and you'd have to destroy it as op to then replace it and modify the seller. What I can do is put an option at the creation to remove the funds to recover option.

- Vending machine now provide a redstone output everytime a player buys an item. Meaning you can activate command blocks etc without overflowing the seller with tons of extra stuff Minecraft is already capable of doing. I recommend you to use that redstone output to do extra stuff, if you see a problem with what I just said, because something could get in the way please let me know!

Thanks for your comment!

**Comment by mr-poyo** [comment]
Thanks! Both solutions would work!
