### ISSUE TITLE
Can't upgrade the credit card, and some requests

### ISSUE THREAD

**Issue by vichocruz** [FifouBE/EconomyInc#25]
Hi! I'm really loving the idea of your mod, and I think it's the best one around for forge, but there is an issue that I've found and I wanted to know if I'm doing something wrong or if it's a bug, but I can't upgrade the card with the microchip. I have tried using it while having the card on the other hand, with shift, without, etc, but nothing works, it only creates a duplicate of the card on the slot where the microchip is, and both says Upgraded:No.
As I'm using this mod in a server, this is a really necessary item to have, because if not we cannot use the vending machine (at least I have made tests trying to buy with the paper dollars, but it doesn't work neither).
Also I wanted to tell you that I've checked the bug that you point in the curse forge webpage, about using hoppers to receive the gold nuggets and everything is fine with that, I can exchange those gold nuggets in the gold changer so I think that bug is corrected.
But I would also love to have a more comfortable way to acquire money, not only with gold nuggets that cannot be stacked... maybe killing mobs, just connecting to the game in different days, selling rotten flesh or things like that IDK.
Anyway, thanks for making this mod, and I'll be following your advance in this mod and testing it in my server.

**Comment by Florent98** [comment]
Hello! Normally you just right click the microchip while having the credit card in your inventory (not in second) normally the microchip should disappear et the card should be upgraded. If you don't have the card, you can still buy in vending machine but you need to have the card in your inventory, if you have microchip you can buy anything without having the credit card in your inventory. 

The bug was for the version 1.6.8 where the recipe for having a pure gold nugget with a weight was to smelt a gold ingot and recovering the nugget, but there was a bug, now I directly pass by the gold changer to "weight" the nugget.

That's something that will come in 1.7 version of the mod, I will rework the seller, and add a machine that can buy items and give money in exchange. For now I don't plan on adding way to get money from killing mob etc, but that could be good to add support for server owners that want to add that kind of thing.  

Thanks for your feedback, please let me know if you still have issues with updating your card! Providing a video if you can so I can see clearly!

**Comment by Florent98** [comment]
Hello.

It's been 2 weeks since my last post, so i consider this issue resolved.

If you have another problem please open a new one.
