### ISSUE TITLE
[1.15.2] Can't use /balance command in datapack functions

### ISSUE THREAD

**Issue by mr-poyo** [FifouBE/EconomyInc#28]
**Forge:** 31.2.5
**Version:** economyinc-1.6.9.1.jar

Hello again!

I am writing a datapack for my server and I came to a point where I would like to call '**balance add @p[tag=daily-01] 5**' through a function, but it doesn't seem to be working.

I am currently using this in my tick.json:
execute at @a[tag=daily-01] run function poyo:daily/daily-01

Once a player is assigned the daily-01 tag, it then calls my **daily/daily-01** function which includes:

say Hello World! (testing)
balance add @p[tag=daily-01] 5
tag @p[tag=daily-01] remove daily-01

I have even tried simplifying the function to just include
Hello World!
balance add @p 5
tag @p[tag=daily-01] remove daily-01

and it won't fire. If i comment out the balance command with #, the Hello World works.
Also, an odd thing, when I perform /reload after server has started (which reloads datapacks), the function starts working again. 

Any ideas on how I could work around this?

**Comment by Florent98** [comment]
Hey!

I think it's due to the fact that the commands needs to be executed by a player and an OP one. If you try running it from the server console it won't work either. I'm going to change that so op player or server can execute this commands.

**Comment by mr-poyo** [comment]
Thanks! Hopefully that will fix it. Oddly enough, I'm already able to add balance via server console. But hopefully this will fix datapacks if you specify server as executor as well.

**Comment by Florent98** [comment]
I checked, and normally you should be able too. Is data pack giving any error that would help ?

**Comment by mr-poyo** [comment]
Hello again,

Here is the error i found in latest.log by CTRL+F searching for main.mcfunction: https://pastebin.com/6trc9gCd

It looks like possibly the command hasn't registered yet? No idea. For this particular log, I re-added the balance to my main function line 4 and commented out all the rest for testing.

![balance](https://user-images.githubusercontent.com/11811815/83813596-a3e4c300-a6f8-11ea-8c28-bdc8459dbb1a.PNG)

At any rate, I have decided to throw Impulse command blocks (since it seems to work fine in command blocks) in my spawn chunks and I trigger them with a simple /data merge command via my datapack function. It's a workaround, but it fits my particular needs.

**Comment by Florent98** [comment]
I have 0 knowledge about datapacks, the illegal argument exception is what is says, basically you are using a word, symbol that is not recognized or not allowed (If I remember correctly) but why ? I have no clue, I'll make some research on my end and ask for help because as I said I don't know datapack at all. 

I'll come back to you with a definitive answer as soon as I can.

**Comment by mr-poyo** [comment]
No worries, if it becomes too much time, please just close and forget for now. I have a workaround to get it working using datapacks and command blocks together. Thanks for your hard work! Looking forward to 1.7.0 (is that the one with the redstone firing on vending blocks? :D)!

**Comment by Florent98** [comment]
No problem! At least you have a workaround but now you made me curious and I would like to know and learn so I can allow it :) The latest version you have already gives redstone output after buy. But I will need to add a cooldown to the button, because it creates problems during lag etc. So that's what I'm working on, and 1.7.0 is redoing the whole seller interface to allow any price, and adding a buying machine so gold changer can disappear.

**Comment by Florent98** [comment]
I still haven't found the source of this problem, but I'm going to check more on datapack to see if it's not a mistype you did, because everything works fine on my end with forge.
