### ISSUE TITLE
The restock feature for Vending machines.

### ISSUE THREAD

**Issue by Saddboi** [FifouBE/EconomyInc#40]
The Mod is pretty amazing and i can make use of it but the Vending machine has an issue or i dont know if is intended. When you place down one and put the Item and set a price in survival of a single item its good until you bought it. then there is no more in stock and it shows that is selling air and cant restock the item you are trying to sell. breaking it and replacing it does nothing because it shows the same item out of stock. also The ./plot create command its confusing for at least me because i cant figure out how big and long is the area i wanna sell, so please do something for the vending machines if i am a dumbass and idk how to use the plot mechanic. Keep what you are doing because you are doing an awsome job. Happy new year. if you ever want to contact me , try on discord Saddboi#0933

**Comment by Florent98** [comment]
Hello! So this is for at least version 1.6.9.4 of the mod, for Minecraft 1.15.x  & 1.16.x

So can you confirm your MC version and version of the mod! Thank you

However, if you have the right version here are some infos :

For seller, when stack is at 0 it will show barrier object. However you can refill with right clicking _your_ seller with the wrench and you should access seller's inventory. Note though, that is a temporary solution as I plan to add a refill option in the near future of the mod.

Normally breaking the seller with the wrench should let you place another one at the same position and you can setup that new seller.

The command seller is used like that 

/plot create firstX firstY firstZ lastX lastY lastZ nameOfThePlot price

first = first block
last = second block

Here is a picture that will probably help you

![EXPLANATIONS_PLOT](https://user-images.githubusercontent.com/30213090/103441931-d6847900-4c51-11eb-9151-e2e3f55b88b4.png)

Note that Y position is literally "useless" but it's best to put the same Y because in any case it will go from max height to bedrock.

Hope this helps.

Happy new year to you!
