### ISSUE TITLE
Both a dupe glitch and a suggestion

### ISSUE THREAD

**Issue by NobodyCentral** [FifouBE/EconomyInc#51]
The dupe first.
Whenever you attempt to apply the microchip to ur card it turns it into any and everything you might be holding in ur off-hand.

The suggestion.
I was wondering if you could update this to 1.18. but I was also wanting to ask if you could make it so that you could just use regular gold nugget in the exchanger (enabled or disabled through the server config file or even not at all?), or at the very least let the proprietary nuggets stack in the furnace.

sorry if I sound kinda rude...

Edit: Crap the title has a typo!
Edit: Ayy... i fixed the typo

EDIT: can we also change the server console spam?

**Comment by Florent98** [comment]
Hello!

The dupe glitch was fixed in the latest version 1.6.9.4.
It's possible, but it would ruin the economy since a ingot gives you 9 nuggets so it would really need to be less money added to your account when you put a gold nugget in the exchanger, but it's a possibility.

I'm planning on removing the console spam by adding a log file completely seperate from the regular one.
